'use strict'
const test = require('node:test')
const assert = require('node:assert/strict')

/**
 * Theme engine integration, executed in sandboxed child processes.
 *
 * The registry resolves its data directory from `DSH_ROOT` when the module is
 * first required, so an in-process test would install themes into the real
 * installation. Every scenario therefore runs against a throwaway project root
 * (see tests/helpers/theme-sandbox.cjs and tests/helpers/theme-suite.cjs).
 *
 * Generated by tests/helpers/generate-theme-engine-test.cjs.
 */
const { runOne, runEach } = require('../helpers/theme-suite.cjs')

test("the full prompt -> preview -> approval -> install pipeline works on a clean install", () => {
  const value = runEach({
    boot: {
      boot: "const paints = []\nconst engine = engineModule.createThemeEngine({\n  log: () => {},\n  applyToRenderer: (payload) => paints.push({ id: payload.id, preview: payload.preview, effect: payload.effectLabel })\n})\nengine.start()\nconst before = engine.describe()\nreturn { paints, active: before.active, themeCount: before.themes.length }",
    },
    create: {
      create: "const engine = engineModule.createThemeEngine({ log: () => {}, applyToRenderer: () => {} })\nengine.start()\n  const result = await engine.orchestrator.createTheme({\n    prompt: '银发角色，黑灰蓝色调，看起来像未来科研工作站，人物别太抢屏'\n  })\n  return {\n    ok: result.ok,\n    stage: result.stage,\n    validationOk: result.validation.ok,\n    failures: result.validation.failures.map((f) => f.id),\n    warnings: result.validation.warnings.length,\n    intent: result.intent,\n    capability: result.capability,\n    snapshot: result.snapshot\n  }",
    },
    notInstalledBeforeApproval: {
      notInstalled: "const engine = engineModule.createThemeEngine({ log: () => {}, applyToRenderer: () => {} })\nengine.start()\n  const created = await engine.orchestrator.createTheme({ prompt: '赛博全息 HUD，黑灰蓝' })\n  const list = engine.describe()\n  const userThemes = list.themes.filter((theme) => theme.source !== 'system' && theme.source !== 'builtin-demo')\n  return {\n    created: created.ok,\n    stage: created.stage,\n    previewing: list.previewing,\n    installed: userThemes.map((theme) => theme.id)\n  }",
    },
    approve: {
      approve: "const engine = engineModule.createThemeEngine({ log: () => {}, applyToRenderer: () => {} })\nengine.start()\n  const created = await engine.orchestrator.createTheme({ prompt: '赛博全息 HUD，黑灰蓝，扫描线' })\n  const approved = engine.orchestrator.approve({ draftId: created.draftId })\n  const after = engine.describe()\n  const record = after.themes.find((theme) => theme.id === approved.id)\n  return {\n    approveOk: approved.ok,\n    stage: approved.stage,\n    id: approved.id,\n    activeAfterApprove: after.active,\n    registered: approved.registered,\n    recordExists: Boolean(record),\n    recordSource: record ? record.source : null,\n    recordActive: record ? record.active : null,\n    recordValidationOk: record ? record.validation.ok : null,\n    previewingAfter: after.previewing\n  }",
    },
    revisionIsIncremental: {
      revision: "const engine = engineModule.createThemeEngine({ log: () => {}, applyToRenderer: () => {} })\nengine.start()\n  const created = await engine.orchestrator.createTheme({ prompt: '银发角色，紫蓝色调，未来科研工作站' })\n  const revised = await engine.orchestrator.reviseTheme({ draftId: created.draftId, prompt: '人物再小一点，按钮不要这么亮' })\n  const session = engine.orchestrator.sessions().get(created.draftId)\n  return {\n    ok: revised.ok,\n    changed: revised.changed,\n    revision: revised.revision,\n    prominenceBefore: created.intent.persona.prominence,\n    prominenceAfter: revised.intent.persona.prominence,\n    designLanguagePreserved: revised.intent.design_language === created.intent.design_language,\n    palettePreserved: JSON.stringify(revised.intent.palette) === JSON.stringify(created.intent.palette),\n    historyLength: session ? (session.history || []).length : 0\n  }",
    },
    discardLeavesNothing: {
      discard: "const engine = engineModule.createThemeEngine({ log: () => {}, applyToRenderer: () => {} })\nengine.start()\n  const created = await engine.orchestrator.createTheme({ prompt: '极简浅色中性' })\n  const discarded = engine.orchestrator.discard({ draftId: created.draftId })\n  const after = engine.describe()\n  return {\n    discarded: discarded.ok,\n    userThemes: after.themes.filter((theme) => theme.source === 'generated').length,\n    previewing: after.previewing\n  }",
    },
  })

  assert.equal(value.boot.active, 'hns.system.dark', 'a clean install starts on the Dark recovery theme')
  assert.equal(value.boot.themeCount, 5, 'installed: Dark, Light and three demo themes')
  assert.ok(value.boot.paints.length >= 1)
  assert.equal(value.boot.paints[0].preview, false)

  assert.equal(value.create.ok, true)
  assert.equal(value.create.stage, 'preview', 'a prompt stops at a preview')
  assert.equal(value.create.validationOk, true, `preview validation failed: ${JSON.stringify(value.create.failures)}`)
  assert.equal(value.create.failures.length, 0)
  assert.equal(value.create.intent.persona.character, 'silver_hair_assistant')
  assert.ok(value.create.intent.persona.prominence <= 0.2)
  assert.ok(value.create.capability.writableSlots > 25)
  assert.equal(value.create.capability.canThemeOfficialUi, false)
  assert.ok(Array.isArray(value.create.capability.states) && value.create.capability.states.length === 10)

  assert.equal(value.notInstalled.created, true)
  assert.equal(value.notInstalled.stage, 'preview')
  assert.equal(value.notInstalled.previewing, true, 'the dock is showing a live preview')
  assert.deepEqual(value.notInstalled.installed, [], 'nothing is installed before approval')

  assert.equal(value.approve.approveOk, true)
  assert.equal(value.approve.stage, 'installed')
  assert.ok(value.approve.id.startsWith('hns.user.'))
  assert.equal(value.approve.recordExists, true)
  assert.equal(value.approve.recordSource, 'generated')
  assert.equal(value.approve.recordActive, true, 'an approved theme becomes active')
  assert.equal(value.approve.recordValidationOk, true)
  assert.equal(value.approve.previewingAfter, false)

  assert.equal(value.revision.ok, true)
  assert.deepEqual(value.revision.changed, ['motion', 'persona'])
  assert.equal(value.revision.revision, 1)
  assert.ok(value.revision.prominenceAfter < value.revision.prominenceBefore)
  assert.equal(value.revision.designLanguagePreserved, true, 'an unmentioned decision survives a revision')
  assert.equal(value.revision.palettePreserved, true)
  assert.equal(value.revision.historyLength, 1)

  assert.equal(value.discard.discarded, true)
  assert.equal(value.discard.userThemes, 0, 'discarding a draft installs nothing')
  assert.equal(value.discard.previewing, false)
})

test("protected system themes can never be deleted, and deleting the active theme returns to Dark", () => {
  const value = runEach({
    protection: {
      protection: "const engine = engineModule.createThemeEngine({ log: () => {}, applyToRenderer: () => {} })\nengine.start()\n  const dark = engine.orchestrator.deleteTheme('hns.system.dark')\n  const light = engine.orchestrator.deleteTheme('hns.system.light')\n  const unknown = engine.orchestrator.deleteTheme('nope')\n  const listed = engine.describe().themes.map((theme) => theme.id)\n  return {\n    dark, light, unknown,\n    darkStillListed: listed.includes('hns.system.dark'),\n    lightStillListed: listed.includes('hns.system.light')\n  }",
    },
    deleteActive: {
      deleteActive: "const engine = engineModule.createThemeEngine({ log: () => {}, applyToRenderer: () => {} })\nengine.start()\n  const created = await engine.orchestrator.createTheme({ prompt: '赛博全息 HUD' })\n  engine.orchestrator.approve({ draftId: created.draftId })\n  const activeId = engine.describe().active\n  const removed = engine.orchestrator.deleteTheme(activeId)\n  const after = engine.describe()\n  return {\n    activeId,\n    removed,\n    activeAfter: after.active,\n    stillListed: after.themes.some((theme) => theme.id === activeId),\n    remaining: after.themes.length\n  }",
    },
    deleteDemo: {
      deleteDemo: "const engine = engineModule.createThemeEngine({ log: () => {}, applyToRenderer: () => {} })\nengine.start()\n  const removed = engine.orchestrator.deleteTheme('hns.demo.cyber-hud')\n  const restored = engine.orchestrator.restoreBuiltin('hns.demo.cyber-hud')\n  const restoreProtected = engine.orchestrator.restoreBuiltin('hns.system.dark')\n  return { removed, restored, restoreProtected, listed: engine.describe().themes.map((t) => t.id) }",
    },
  })

  assert.equal(value.protection.dark.ok, false)
  assert.equal(value.protection.dark.reason, 'protected')
  assert.equal(value.protection.light.reason, 'protected')
  assert.equal(value.protection.unknown.reason, 'not_found')
  assert.equal(value.protection.darkStillListed, true)
  assert.equal(value.protection.lightStillListed, true)

  assert.equal(value.deleteActive.removed.ok, true)
  assert.equal(value.deleteActive.removed.switchedTo, 'hns.system.dark', 'deleting the active theme switches to Dark first')
  assert.equal(value.deleteActive.activeAfter, 'hns.system.dark')
  assert.equal(value.deleteActive.stillListed, false)
  assert.ok(value.deleteActive.remaining >= 5)

  assert.equal(value.deleteDemo.removed.ok, true)
  assert.equal(value.deleteDemo.restored.ok, true, `a built-in demo theme can be restored after deletion: ${value.deleteDemo.restored.reason || ''}`)
  assert.equal(value.deleteDemo.restoreProtected.reason, 'protected', 'a system theme cannot be factory-restored either')
  assert.deepEqual(value.deleteDemo.hidden || [], [], 'restoring clears the hidden marker')
  assert.ok(value.deleteDemo.listed.includes('hns.demo.cyber-hud'), `the restored demo is listed again: restored=${JSON.stringify(value.deleteDemo.restored)} hidden=${JSON.stringify(value.deleteDemo.hidden)} listed=${JSON.stringify(value.deleteDemo.listed)}`)
})

test("duplication produces a self-contained copy with no runtime link to its source", () => {
  const value = runEach({
    duplicate: {
      duplicate: "const fs = require('node:fs')\nconst path = require('node:path')\nconst engine = engineModule.createThemeEngine({ log: () => {}, applyToRenderer: () => {} })\nengine.start()\nconst copied = engine.orchestrator.duplicateTheme('hns.demo.cyber-hud', { name: 'cyber copy' })\nif (!copied.ok) {\n  return { ok: false, error: copied.reason, issues: (copied.issues || []).map((issue) => issue.message) }\n}\nconst copyManifest = JSON.parse(fs.readFileSync(path.join(copied.dir, 'manifest.json'), 'utf8'))\nconst copyTokens = JSON.parse(fs.readFileSync(path.join(copied.dir, 'tokens.json'), 'utf8'))\nconst hasWallpaper = fs.existsSync(path.join(copied.dir, 'assets', 'wallpapers', 'main.png'))\n// Deleting the source template must not disturb the copy.\nengine.orchestrator.deleteTheme('hns.demo.cyber-hud')\nconst afterDelete = engine.lifecycle.inspectTheme(copied.id)\nreturn {\n  ok: true,\n  id: copied.id,\n  from: copied.from,\n  derivedFrom: copyManifest.derived_from,\n  copyHasOwnAssets: hasWallpaper,\n  copyHasOwnTokens: Object.keys(copyTokens).length > 20,\n  copySurvivesSourceDeletion: afterDelete.ok,\n  copyValidationOk: afterDelete.ok ? afterDelete.record.validation.ok : false,\n  noParentField: !Object.prototype.hasOwnProperty.call(copyManifest, 'parent_theme') && !Object.prototype.hasOwnProperty.call(copyManifest, 'required_theme')\n}",
    },
  })

  assert.equal(value.duplicate.ok, true, `duplication failed: ${value.duplicate.error || ''} ${JSON.stringify(value.duplicate.issues || [])}`)
  assert.notEqual(value.duplicate.id, value.duplicate.from)
  assert.equal(value.duplicate.derivedFrom, 'hns.demo.cyber-hud')
  assert.equal(value.duplicate.copyHasOwnAssets, true)
  assert.equal(value.duplicate.copyHasOwnTokens, true)
  assert.equal(value.duplicate.noParentField, true, 'no runtime dependency field is written')
  assert.equal(value.duplicate.copySurvivesSourceDeletion, true, 'deleting the source theme cannot affect the copy')
  assert.equal(value.duplicate.copyValidationOk, true)
})

test("a broken package recovers to Dark instead of taking the dock down", () => {
  const value = runEach({
    recovery: {
      recovery: "const fs = require('node:fs')\nconst path = require('node:path')\nconst engine = engineModule.createThemeEngine({ log: () => {}, applyToRenderer: () => {} })\nengine.start()\nconst created = await engine.orchestrator.createTheme({ prompt: '二次元角色，紫蓝色调' })\nconst approved = engine.orchestrator.approve({ draftId: created.draftId })\n// Corrupt the installed theme the way a disk failure would.\nfs.writeFileSync(path.join(approved.dir, 'manifest.json'), '{ broken', 'utf8')\nconst record = engine.registry.list().find((theme) => theme.id === approved.id)\nconst applied = engine.orchestrator.applyTheme(approved.id)\nconst paint = engine.paintPayload()\nreturn {\n  markedBroken: record ? record.broken : null,\n  brokenCodes: record ? record.validation.issues.filter((i) => i.severity === 'error').map((i) => i.code) : [],\n  applyOk: applied.ok,\n  applyReason: applied.reason,\n  recovered: applied.recovered,\n  activeAfter: engine.describe().active,\n  paintId: paint.id,\n  paintTokens: Object.keys(paint.tokens || {}).length\n}",
    },
    missingAssetRecovery: {
      missingAsset: "const fs = require('node:fs')\nconst path = require('node:path')\nconst engine = engineModule.createThemeEngine({ log: () => {}, applyToRenderer: () => {} })\nengine.start()\nconst created = await engine.orchestrator.createTheme({ prompt: '赛博全息 HUD' })\nconst approved = engine.orchestrator.approve({ draftId: created.draftId })\n// Remove the compiled asset files: the package is now incomplete.\nfs.rmSync(path.join(approved.dir, 'assets'), { recursive: true, force: true })\nconst record = engine.registry.list().find((theme) => theme.id === approved.id)\nconst applied = engine.orchestrator.applyTheme(approved.id)\nreturn {\n  broken: record ? record.broken : null,\n  codes: record ? record.validation.issues.filter((i) => i.severity === 'error').map((i) => i.code) : [],\n  recovered: applied.recovered,\n  active: engine.describe().active\n}",
    },
    fallbackConstants: {
      fallback: "const recovery = requireApp('extensions/mega/theme/recovery')\nconst contract = requireApp('extensions/mega/theme/contract')\nconst theme = recovery.fallbackTheme('hns.system.dark')\nreturn {\n  tokenCount: Object.keys(theme.tokens).length,\n  expected: contract.TOKEN_NAMES.length,\n  slotCount: Object.keys(theme.components.slots).length,\n  assetsNeutralised: theme.tokens['asset.wallpaper'] === 'none',\n  personaOff: theme.persona.enabled === false\n}",
    },
  })

  assert.equal(value.recovery.markedBroken, true, 'an unparsable manifest marks the record broken')
  assert.ok(value.recovery.brokenCodes.includes('manifest_unparsable'))
  assert.equal(value.recovery.applyOk, false, 'applying a broken theme is refused')
  assert.equal(value.recovery.recovered, true)
  assert.equal(value.recovery.activeAfter, 'hns.system.dark', 'the engine falls back to Dark')
  assert.equal(value.recovery.paintId, 'hns.system.dark')
  assert.ok(value.recovery.paintTokens > 20, 'the dock still receives a complete paint payload')

  assert.equal(value.missingAsset.broken, true)
  assert.ok(value.missingAsset.codes.includes('asset_missing'))
  assert.equal(value.missingAsset.recovered, true)
  assert.equal(value.missingAsset.active, 'hns.system.dark')

  assert.equal(value.fallback.tokenCount, value.fallback.expected)
  assert.ok(value.fallback.slotCount > 20)
  assert.equal(value.fallback.assetsNeutralised, true)
  assert.equal(value.fallback.personaOff, true)
})

test("import copies a package into the user theme directory as a self-contained theme", () => {
  const value = runEach({
    import: {
      import: "const path = require('node:path')\nconst engine = engineModule.createThemeEngine({ log: () => {}, applyToRenderer: () => {} })\nengine.start()\n// Build a standalone package the way another installation would export it.\nconst draft = engine.designer.design({ intent: engine.designer.interpret('极简浅色中性，低装饰') })\nconst outDir = path.join(process.env.DSH_ROOT, 'incoming-theme')\nconst built = engine.builder.buildPackage({\n  draft, id: 'vendored.theme', name: 'Vendored Theme', outDir, source: 'generated'\n})\nconst imported = engine.orchestrator.importTheme(outDir, { name: 'Vendored' })\nconst record = imported.ok ? engine.registry.list().find((theme) => theme.id === imported.id) : null\nreturn {\n  built: built.ok,\n  imported,\n  recordSource: record ? record.source : null,\n  recordName: record ? record.name : null,\n  manifestIdMatches: record ? record.id === imported.id : false\n}",
    },
  })

  assert.equal(value.import.built, true)
  assert.equal(value.import.imported.ok, true)
  assert.equal(value.import.recordSource, 'imported')
  assert.equal(value.import.recordName, 'Vendored')
  assert.equal(value.import.manifestIdMatches, true)
})

test("the runtime degrades heavy effects under load without touching the theme package", () => {
  const value = runEach({
    degradation: {
      degradation: "let load = { cpuPercent: 10, freeGb: 8, running: 0, slots: 4, capacity: 4 }\nconst engine = engineModule.createThemeEngine({\n  log: () => {},\n  scheduler: {\n    describe: () => ({\n      system: { cpu: { usagePercent: load.cpuPercent }, memory: { freeGb: load.freeGb } },\n      activeQueue: { running: load.running, workerSlotsInUse: load.slots },\n      concurrency: { current: load.capacity }\n    })\n  },\n  applyToRenderer: () => {}\n})\nengine.start()\nconst created = await engine.orchestrator.createTheme({ prompt: '赛博全息 HUD，强烈动感，装饰丰富' })\nengine.orchestrator.approve({ draftId: created.draftId })\nconst idle = engine.paintPayload()\n\n// Load spikes: the runtime must down-grade, not fail.\nload = { cpuPercent: 97, freeGb: 0.4, running: 4, slots: 4, capacity: 4 }\nengine.runtime.sampleLoad()\nconst loadedPaint = engine.paintPayload()\n\n// Recovery: effects come back.\nload = { cpuPercent: 5, freeGb: 9, running: 0, slots: 4, capacity: 4 }\nengine.runtime.sampleLoad()\nconst restored = engine.runtime.describe()\n\nconst record = engine.registry.list().find((theme) => theme.id === created.themeId)\nreturn {\n  idleLevel: idle.effectLevel,\n  loadedLevel: loadedPaint.effectLevel,\n  loadedLabel: loadedPaint.effectLabel,\n  loadedAnimation: loadedPaint.animation,\n  idleAnimation: idle.animation,\n  loadedWallpaperNeutralised: loadedPaint.tokens['asset.wallpaper'] === 'none',\n  restoredLevel: restored.effectLevel,\n  packageUntouched: record ? record.validation.ok : false\n}",
    },
  })

  assert.equal(value.degradation.idleLevel, 0)
  assert.equal(value.degradation.loadedLevel, 2, 'a saturated machine drops to the minimal effect budget')
  assert.equal(value.degradation.loadedAnimation.type, 'none')
  assert.equal(value.degradation.loadedWallpaperNeutralised, true, 'heavy assets are dropped under load')
  assert.equal(value.degradation.restoredLevel, 0, 'effects return when the load clears')
  assert.equal(value.degradation.packageUntouched, true, 'degradation never edits the installed theme package')
})

test("the capability manifest describes what may be themed and what may not", () => {
  const value = runEach({
    manifest: {
      manifest: "const engine = engineModule.createThemeEngine({ log: () => {}, applyToRenderer: () => {} })\nengine.start()\n  const manifest = engine.capabilities()\n  const permissions = Object.values(manifest.slots).map((slot) => slot.permission)\n  return {\n    app: manifest.app,\n    apiVersion: manifest.theme_api_version,\n    surfaces: manifest.themeable_surfaces.map((s) => ({ id: s.id, themable: s.themable, hint: Boolean(s.paletteHintOnly) })),\n    states: manifest.states,\n    animations: manifest.capabilities.animations,\n    canThemeOfficial: manifest.capabilities.can_theme_official_ui,\n    personaMax: manifest.capabilities.persona_max_prominence,\n    layoutOverride: manifest.capabilities.layout_override,\n    structuralCount: permissions.filter((p) => p === 'STRUCTURAL').length,\n    writableCount: permissions.filter((p) => p !== 'STRUCTURAL').length,\n    protectedRegions: manifest.protected_regions.map((region) => region.id),\n    pages: manifest.pages.map((page) => page.id)\n  }",
    },
  })

  assert.equal(value.manifest.app, 'hns')
  assert.equal(value.manifest.apiVersion, '1.0')
  assert.equal(value.manifest.canThemeOfficial, false, 'the official renderer is never claimed as themable')
  assert.equal(value.manifest.layoutOverride, false, 'structural layout is never offered to the generator')
  assert.equal(value.manifest.personaMax, 0.4)
  assert.ok(value.manifest.structuralCount >= 3)
  assert.ok(value.manifest.writableCount >= 30)
  assert.equal(value.manifest.states.length, 10)
  assert.ok(value.manifest.animations.includes('soft_blur'))
  assert.deepEqual(value.manifest.surfaces.find((s) => s.id === 'official'), { id: 'official', themable: false, hint: true }, 'the official UI is exposed as a palette hint only')
  assert.ok(value.manifest.protectedRegions.includes('queue-create'))
  assert.ok(value.manifest.pages.includes('dashboard'))
})

test("every theme paint payload is declarative data, never executable content", () => {
  const value = runEach({
    payload: {
      systemPayload: "const engine = engineModule.createThemeEngine({ log: () => {}, applyToRenderer: () => {} })\nengine.start()\n  const paint = engine.paintPayload()\n  const forbidden = /<script|javascript:|onerror=|onload=|eval\\(|new Function/i\n  return {\n    keys: Object.keys(paint).sort(),\n    cssIsVarDeclarationsOnly: paint.css.split('\\n').every((line) => line.trim() === '' || /^--hns-[a-z0-9-]+: .+;$/.test(line.trim())),\n    tokensInCss: paint.css.includes('--hns-color-bg-base:'),\n    noExecutable: !forbidden.test(JSON.stringify(paint)),\n    assetsAreDataUris: Object.entries(paint.tokens)\n      .filter(([name]) => name.startsWith('asset.'))\n      .every(([, value]) => value === 'none' || String(value).startsWith('data:image/')),\n    personaConfined: paint.slots['hns.operator.widget'].position === 'corner-bottom-right'\n  }",
    },
    userThemePayload: {
      userPayload: "const engine = engineModule.createThemeEngine({ log: () => {}, applyToRenderer: () => {} })\nengine.start()\n  const created = await engine.orchestrator.createTheme({ prompt: '二次元银发角色，紫蓝色调，装饰丰富' })\n  const approved = engine.orchestrator.approve({ draftId: created.draftId })\n  const paint = engine.paintPayload()\n  const forbidden = /<script|javascript:|onerror=|onload=|eval\\(|new Function/i\n  return {\n    approved: approved.ok,\n    noExecutable: !forbidden.test(JSON.stringify(paint)),\n    hasWallpaperDataUri: String(paint.tokens['asset.wallpaper']).startsWith('data:image/png;base64,'),\n    hasAvatarDataUri: String(paint.tokens['asset.persona_avatar']).startsWith('data:image/png;base64,'),\n    personaEnabled: paint.persona.enabled\n  }",
    },
  })

  assert.deepEqual(value.systemPayload.keys, ['animation', 'css', 'draftId', 'effectLabel', 'effectLevel', 'id', 'name', 'officialPalette', 'persona', 'preview', 'slots', 'tokens'].sort())
  assert.equal(value.systemPayload.cssIsVarDeclarationsOnly, true, 'the paint payload only carries CSS custom properties')
  assert.equal(value.systemPayload.tokensInCss, true)
  assert.equal(value.systemPayload.noExecutable, true)
  assert.equal(value.systemPayload.assetsAreDataUris, true)
  assert.equal(value.systemPayload.personaConfined, true)

  assert.equal(value.userPayload.approved, true)
  assert.equal(value.userPayload.noExecutable, true)
  assert.equal(value.userPayload.hasWallpaperDataUri, true)
  assert.equal(value.userPayload.hasAvatarDataUri, true)
  assert.equal(value.userPayload.personaEnabled, true)
})

test("the installed theme directory layout matches the documented package structure", () => {
  const value = runEach({
    layout: {
      layout: "const fs = require('node:fs')\nconst path = require('node:path')\nconst engine = engineModule.createThemeEngine({ log: () => {}, applyToRenderer: () => {} })\nengine.start()\nconst created = await engine.orchestrator.createTheme({ prompt: '二次元银发角色，装饰丰富' })\nconst approved = engine.orchestrator.approve({ draftId: created.draftId })\nconst manifest = JSON.parse(fs.readFileSync(path.join(approved.dir, 'manifest.json'), 'utf8'))\nreturn {\n  entries: fs.readdirSync(approved.dir).sort(),\n  assets: fs.readdirSync(path.join(approved.dir, 'assets')).sort(),\n  manifestFields: Object.keys(manifest).sort(),\n  revisionHistory: manifest.revision_history.length,\n  hasPrompt: typeof manifest.generated_prompt === 'string' && manifest.generated_prompt.length > 0,\n  installedAt: Boolean(manifest.installed_at),\n  previewPng: fs.existsSync(path.join(approved.dir, 'preview.png')),\n  previewHtml: fs.existsSync(path.join(approved.dir, 'preview.html')),\n  insideUserThemes: approved.dir.startsWith(engine.registry.userThemesDir())\n}",
    },
  })

  for (const required of ['manifest.json', 'tokens.json', 'components.json', 'persona.json', 'preview.png', 'preview.html', 'assets']) {
  assert.ok(value.layout.entries.includes(required), `installed package contains ${required}`)
}
  for (const required of ['decorations', 'icons', 'panels', 'persona', 'wallpapers']) {
  assert.ok(value.layout.assets.includes(required), `assets/ contains ${required}`)
}
  for (const field of ['id', 'name', 'version', 'source', 'protected', 'theme_api_version', 'supported_apps', 'created_at', 'generated_prompt', 'revision_history', 'derived_from']) {
  assert.ok(value.layout.manifestFields.includes(field), `manifest declares ${field}`)
}
  assert.equal(value.layout.insideUserThemes, true)
  assert.equal(value.layout.previewPng, true)
  assert.equal(value.layout.previewHtml, true)
  assert.equal(value.layout.revisionHistory, 1)
  assert.equal(value.layout.hasPrompt, true)
  assert.equal(value.layout.installedAt, true)
})

test("the theme registry survives a reload and stays consistent with disk", () => {
  const value = runEach({
    persistence: {
      persistence: "const fs = require('node:fs')\nconst path = require('node:path')\nconst engine = engineModule.createThemeEngine({ log: () => {}, applyToRenderer: () => {} })\nengine.start()\nconst created = await engine.orchestrator.createTheme({ prompt: '深色工业监控台，冷灰钢蓝' })\nconst approved = engine.orchestrator.approve({ draftId: created.draftId })\nengine.stop()\nconst active = JSON.parse(fs.readFileSync(path.join(process.env.DSH_ROOT, 'data', 'state', 'theme-active.json'), 'utf8'))\nconst registry = JSON.parse(fs.readFileSync(path.join(process.env.DSH_ROOT, 'data', 'state', 'theme-registry.json'), 'utf8'))\n\n// A fresh engine instance must see exactly the same world.\nconst reloaded = engineModule.createThemeEngine({ log: () => {}, applyToRenderer: () => {} })\nreloaded.start()\nconst after = reloaded.describe()\nconst record = after.themes.find((theme) => theme.id === approved.id)\nreturn {\n  activeId: active.id,\n  registryEntries: registry.themes.map((entry) => ({ id: entry.id, source: entry.source, protected: entry.protected, hasPrompt: Boolean(entry.generated_prompt), hasApi: entry.theme_api_version === '1.0' })),\n  reloadActive: after.active,\n  reloadSeesTheme: Boolean(record),\n  reloadRecordValidationOk: record ? record.validation.ok : false\n}",
    },
  })

  assert.ok(value.persistence.activeId.startsWith('hns.user.'))
  assert.equal(value.persistence.reloadActive, value.persistence.activeId, 'the active theme survives a restart')
  assert.equal(value.persistence.reloadSeesTheme, true)
  assert.equal(value.persistence.reloadRecordValidationOk, true)
  const entry = value.persistence.registryEntries.find((item) => item.id === value.persistence.activeId)
  assert.ok(entry, 'the user theme is recorded in the registry file')
  assert.equal(entry.protected, false)
  assert.equal(entry.hasPrompt, true)
  assert.equal(entry.hasApi, true)
  assert.ok(!value.persistence.registryEntries.some((item) => item.source === 'system'), 'system themes are never written to the user registry')
})

test("theme files never land outside their own directory", () => {
  const value = runEach({
    isolation: {
      isolation: "const fs = require('node:fs')\nconst path = require('node:path')\nconst engine = engineModule.createThemeEngine({ log: () => {}, applyToRenderer: () => {} })\nengine.start()\nconst dataDir = path.join(process.env.DSH_ROOT, 'data')\nconst before = fs.readdirSync(dataDir).sort()\nconst created = await engine.orchestrator.createTheme({ prompt: '深色工业监控台，冷灰钢蓝' })\nconst approved = engine.orchestrator.approve({ draftId: created.draftId })\nconst after = fs.readdirSync(dataDir).sort()\nconst files = []\nconst walk = (dir) => {\n  for (const item of fs.readdirSync(dir, { withFileTypes: true })) {\n    const full = path.join(dir, item.name)\n    if (item.isDirectory()) walk(full)\n    else files.push(path.relative(approved.dir, full))\n  }\n}\nwalk(approved.dir)\nreturn {\n  dataEntriesAdded: after.filter((item) => !before.includes(item)),\n  escapes: files.filter((file) => file.startsWith('..')),\n  fileCount: files.length\n}",
    },
  })

  assert.deepEqual(value.isolation.escapes, [])
  assert.ok(value.isolation.fileCount > 8)
  for (const entry of value.isolation.dataEntriesAdded) {
  assert.ok(['themes', 'theme-workspace', 'state'].includes(entry), `unexpected data entry ${entry}`)
}
})

test("the demo themes shipped in the repository are valid, self-contained packages", () => {
  const value = runEach({
    demos: {
      demos: "const fs = require('node:fs')\nconst path = require('node:path')\nconst validator = requireApp('extensions/mega/theme/validator')\nconst builtin = path.join(app, 'extensions', 'mega', 'theme', 'builtin')\nconst results = []\nfor (const relative of ['system/dark', 'system/light', 'demo/minimal-neutral', 'demo/anime-persona', 'demo/cyber-hud']) {\n  const dir = path.join(builtin, relative)\n  const report = validator.validatePackage({ dir })\n  const manifest = JSON.parse(fs.readFileSync(path.join(dir, 'manifest.json'), 'utf8'))\n  results.push({\n    relative,\n    ok: report.ok,\n    errors: report.errors.map((e) => e.code),\n    protected: Boolean(manifest.protected),\n    deletable: manifest.deletable,\n    source: manifest.source,\n    hasPreview: fs.existsSync(path.join(dir, 'preview.png')) || manifest.source === 'system'\n  })\n}\nreturn { results }",
    },
  })

  for (const demo of value.demos.results) {
  assert.ok(demo.ok, `${demo.relative} must validate: ${demo.errors.join(', ')}`)
  assert.equal(demo.hasPreview, true, `${demo.relative} ships a preview`)
}
  const byRelative = Object.fromEntries(value.demos.results.map((item) => [item.relative, item]))
  assert.equal(byRelative['system/dark'].protected, true)
  assert.equal(byRelative['system/dark'].deletable, false)
  assert.equal(byRelative['system/light'].protected, true)
  assert.equal(byRelative['demo/cyber-hud'].protected, false)
  assert.equal(byRelative['demo/cyber-hud'].deletable, true)
})

